In [2]:
import pandas as pd

file = "modern_arts.csv"

data = pd.read_csv(file)

In [3]:
data.head(10)

,Title,Artist,Nationality,BeginDate,EndDate,Gender,Date,Department
0,Dress MacLeod from Tartan Sets,Sarah Charlesworth,(American),(1947),(2013),(Female),1986,Prints & Illustrated Books
1,Duplicate of plate from folio 11 verso (supple...,Pablo Palazuelo,(Spanish),(1916),(2007),(Male),1978,Prints & Illustrated Books
2,Tailpiece (page 55) from SAGESSE,Maurice Denis,(French),(1870),(1943),(Male),1889-1911,Prints & Illustrated Books
3,Headpiece (page 129) from LIVRET DE FOLASTRIES...,Aristide Maillol,(French),(1861),(1944),(Male),1927-1940,Prints & Illustrated Books
4,97 rue du Bac,Eugène Atget,(French),(1857),(1927),(Male),1903,Photography
5,Pictorial ornament (folio 11) from WOODCUTS,Antonio Frasconi,(American),(1919),(2013),(Male),1957,Prints & Illustrated Books
6,Rue de l'Hôtel-de-Ville,Eugène Atget,(French),(1857),(1927),(Male),1924,Photography
7,Los Angeles Airport,Garry Winogrand,(American),(1928),(1984),(Male),1978-1983,Photography
8,Why Defy from Disasters of Peace,Diane Victor,(South African),(1964),NaN,(Female),2001,Prints & Illustrated Books
9,STILL WATER AND FISH,David Brown Milne,(Canadian),(1882),(1953),(Male),(1941),Prints & Illustrated Books

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16725 entries, 0 to 16724
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        16724 non-null  object
 1   Artist       16725 non-null  object
 2   Nationality  16725 non-null  object
 3   BeginDate    15786 non-null  object
 4   EndDate      10474 non-null  object
 5   Gender       16725 non-null  object
 6   Date         16725 non-null  object
 7   Department   16725 non-null  object
dtypes: object(8)
memory usage: 1.0+ MB

In [5]:
#cleaning nationality column

data["Nationality"] = data["Nationality"].str.replace("(" , "").str.replace(")" , "")
data["Nationality"] = data["Nationality"].str.title()
bol = data["Nationality"] == ''
data.loc[bol , "Nationality"] = "Nationality Unknown"

In [6]:
#cleaning Gender column

data["Gender"] = data["Gender"].str.replace("(" , "").str.replace(")" , "")
data["Gender"] = data["Gender"].str.title()
bol2 = data["Gender"] == ''
data.loc[bol2 , "Gender"] = "Gender Unknown"

In [10]:
#cleaning dates column

data["BeginDate"] = data["BeginDate"].str.replace("(" , "").str.replace(")" , "").astype(float)

data["EndDate"] = data["EndDate"].str.replace("(" , "").str.replace(")" , "").astype(float)

bad_char = ["c" , "C" , "." , " " , "..." , "s" , "(" , ")"]

def clear_date(date):
    for i in bad_char:
        date = date.replace(i , "")
    return date

'def separate(dates):\n    if "-" in dates:\n        lst = dates.split("-")\n        year1 = int(lst[0])\n        year2 = int(lst[1])\n        dates = round((year1+year2)/2)\n    else:\n        dates = int(dates)\n    return dates\n\nif "-" in data["Date"]:\n    lst = data["Dates"].split("-")\n    year1 = int(lst[0])\n    year2 = int(lst[1])\n    data["Date"] = round((year1+year2)/2) \nelse:\n    data["Date"] = int(data["Date"])'

In [11]:
data["Date"] = data["Date"].apply(clear_date)

In [13]:
data.head(10)

,Title,Artist,Nationality,BeginDate,EndDate,Gender,Date,Department
0,Dress MacLeod from Tartan Sets,Sarah Charlesworth,American,1947.0,2013.0,Female,1986,Prints & Illustrated Books
1,Duplicate of plate from folio 11 verso (supple...,Pablo Palazuelo,Spanish,1916.0,2007.0,Male,1978,Prints & Illustrated Books
2,Tailpiece (page 55) from SAGESSE,Maurice Denis,French,1870.0,1943.0,Male,1889-1911,Prints & Illustrated Books
3,Headpiece (page 129) from LIVRET DE FOLASTRIES...,Aristide Maillol,French,1861.0,1944.0,Male,1927-1940,Prints & Illustrated Books
4,97 rue du Bac,Eugène Atget,French,1857.0,1927.0,Male,1903,Photography
5,Pictorial ornament (folio 11) from WOODCUTS,Antonio Frasconi,American,1919.0,2013.0,Male,1957,Prints & Illustrated Books
6,Rue de l'Hôtel-de-Ville,Eugène Atget,French,1857.0,1927.0,Male,1924,Photography
7,Los Angeles Airport,Garry Winogrand,American,1928.0,1984.0,Male,1978-1983,Photography
8,Why Defy from Disasters of Peace,Diane Victor,South African,1964.0,NaN,Female,2001,Prints & Illustrated Books
9,STILL WATER AND FISH,David Brown Milne,Canadian,1882.0,1953.0,Male,1941,Prints & Illustrated Books